import { Artisan, City, Profession , Product } from "../types/types";

export const artisans: Artisan[] = [
  {
    id: 1,
    nom: "Amine Saadi",
    metier: Profession.Plumber,
    ville: City.Casablanca,
    quartier: "Maârif",
    telephone: "0612345678",
    description: "Spécialiste en fuites, installations sanitaires et chauffage. Disponible 24/7.",
    available247: true
  },
  {
    id: 2,
    nom: "Fatima Benani",
    metier: Profession.Electrician,
    ville: City.Rabat,
    quartier: "Agdal",
    telephone: "0698765432",
    description: "Installation, réparation et mise aux normes de systèmes électriques pour particuliers.",
  },
  {
    id: 3,
    nom: "Youssef Cherkaoui",
    metier: Profession.Painter,
    ville: City.Marrakech,
    quartier: "Gueliz",
    telephone: "0611223344",
    description: "Peinture intérieure et extérieure, enduit, décoration et finitions soignées.",
  },
  {
    id: 4,
    nom: "Karim Tazi",
    metier: Profession.Carpenter,
    ville: City.Casablanca,
    quartier: "Ain Diab",
    telephone: "0655443322",
    description: "Menuiserie bois et aluminium, placards sur mesure et réparation de meubles.",
  },
  {
    id: 5,
    nom: "Nadia El Fassi",
    metier: Profession.ACSpecialist,
    ville: City.Tanger,
    quartier: "Malabata",
    telephone: "0677889900",
    description: "Installation et entretien de climatiseurs. Service rapide en été.",
  },
  {
    id: 6,
    nom: "Hassan Idrissi",
    metier: Profession.Mechanic,
    ville: City.Fes,
    quartier: "Ville Nouvelle",
    telephone: "0622334455",
    description: "Mécanique générale auto, diagnostic électronique et vidange à domicile.",
  },
  {
    id: 7,
    nom: "Omar Berrada",
    metier: Profession.Gardener,
    ville: City.Rabat,
    quartier: "Souissi",
    telephone: "0644556677",
    description: "Entretien de jardins, taille de haies, plantation et systèmes d'arrosage.",
  },
  {
    id: 8,
    nom: "Samira Alami",
    metier: Profession.Plumber,
    ville: City.Marrakech,
    quartier: "Hivernage",
    telephone: "0688776655",
    description: "Plomberie d'urgence, débouchage canalisation et réparation chauffe-eau.",
    available247: true
  },
  {
    id: 9,
    nom: "Rachid Bennani",
    metier: Profession.Electrician,
    ville: City.Casablanca,
    quartier: "Sidi Bernoussi",
    telephone: "0633221100",
    description: "Électricien expérimenté pour installations industrielles et domestiques.",
  },
  {
    id: 10,
    nom: "Leila Mansouri",
    metier: Profession.Painter,
    ville: City.Tanger,
    quartier: "Centre Ville",
    telephone: "0699887766",
    description: "Rénovation de façades et peinture décorative. Devis gratuit.",
  },
  {
    id: 11,
    nom: "Ahmed Kabbaj",
    metier: Profession.Carpenter,
    ville: City.Fes,
    quartier: "Medina",
    telephone: "0611122233",
    description: "Artisan menuisier traditionnel, portes sculptées et fenêtres.",
  },
  {
    id: 12,
    nom: "Tariq Bouzidi",
    metier: Profession.ACSpecialist,
    ville: City.Agadir,
    quartier: "Talborjt",
    telephone: "0655667788",
    description: "Réparation frigos et climatisation. Déplacement dans tout Agadir.",
  },
  {
    id: 13,
    nom: "Mustapha Zaki",
    metier: Profession.Mechanic,
    ville: City.Casablanca,
    quartier: "Derb Ghallef",
    telephone: "0622114433",
    description: "Spécialiste réparation motos et scooters. Pièces de rechange disponibles.",
  },
  {
    id: 14,
    nom: "Khadija Ouazzani",
    metier: Profession.Gardener,
    ville: City.Marrakech,
    quartier: "Palmeraie",
    telephone: "0677788899",
    description: "Création d'espaces verts, entretien de palmiers et gazon.",
  },
  {
    id: 15,
    nom: "Driss Chraibi",
    metier: Profession.Plumber,
    ville: City.Rabat,
    quartier: "Hay Riad",
    telephone: "0600112233",
    description: "Plomberie de luxe, installation de salles de bain modernes.",
  },
  {
    id: 16,
    nom: "Meryem Hassar",
    metier: Profession.Electrician,
    ville: City.Agadir,
    quartier: "Sonaba",
    telephone: "0699001122",
    description: "Dépannage électrique rapide. Installation de caméras de surveillance.",
  },
  {
    id: 17,
    nom: "Khalid Daoudi",
    metier: Profession.Painter,
    ville: City.Casablanca,
    quartier: "Bourgogne",
    telephone: "0644332211",
    description: "Papier peint, peinture à effet, stuc. Travail propre et rapide.",
  },
  {
    id: 18,
    nom: "Salma Fassi",
    metier: Profession.Carpenter,
    ville: City.Rabat,
    quartier: "Océan",
    telephone: "0688990011",
    description: "Réparation de volets roulants et menuiserie aluminium.",
  },
  {
    id: 19,
    nom: "Mehdi Jettou",
    metier: Profession.ACSpecialist,
    ville: City.Marrakech,
    quartier: "Daoudiate",
    telephone: "0612312312",
    description: "Maintenance VMC et climatisation réversible.",
  },
  {
    id: 20,
    nom: "Brahim El Alami",
    metier: Profession.Mechanic,
    ville: City.Tanger,
    quartier: "Beni Makada",
    telephone: "0676543210",
    description: "Garagiste expert toutes marques. Diagnostic valise.",
  },
  {
    id: 21,
    nom: "Souad Filali",
    metier: Profession.Gardener,
    ville: City.Casablanca,
    quartier: "Californie",
    telephone: "0654321098",
    description: "Paysagiste, aménagement de terrasses et jardins.",
  },
  {
    id: 22,
    nom: "Reda Tazi",
    metier: Profession.Plumber,
    ville: City.Fes,
    quartier: "Narjiss",
    telephone: "0611223399",
    description: "Recherche de fuite non destructive. Débouchage haute pression.",
  },
  {
    id: 23,
    nom: "Zineb Bennani",
    metier: Profession.Electrician,
    ville: City.Marrakech,
    quartier: "Massira",
    telephone: "0699887711",
    description: "Électricité bâtiment. Mise en conformité.",
  },
  {
    id: 24,
    nom: "Yassine Alaoui",
    metier: Profession.Painter,
    ville: City.Rabat,
    quartier: "Hassan",
    telephone: "0622334411",
    description: "Peintre en bâtiment, ravalement de façade.",
  },
  {
    id: 25,
    nom: "Noura Amrani",
    metier: Profession.Carpenter,
    ville: City.Tanger,
    quartier: "Charf",
    telephone: "0677889922",
    description: "Cuisines équipées sur mesure et dressings.",
  },
  {
    id: 26,
    nom: "Fouad Bennis",
    metier: Profession.ACSpecialist,
    ville: City.Casablanca,
    quartier: "Oulfa",
    telephone: "0633445566",
    description: "Froid industriel et commercial. Contrats d'entretien.",
  },
  {
    id: 27,
    nom: "Aicha Kadiri",
    metier: Profession.Mechanic,
    ville: City.Agadir,
    quartier: "Dakhla",
    telephone: "0612341234",
    description: "Pneumatiques, équilibrage et parallélisme.",
  },
  {
    id: 28,
    nom: "Mouad Hilali",
    metier: Profession.Plumber,
    ville: City.Tanger,
    quartier: "Mesnana",
    telephone: "0698769876",
    description: "Installation sanitaire complète pour nouvelles constructions.",
  },
  {
    id: 29,
    nom: "Hanan Touimi",
    metier: Profession.Electrician,
    ville: City.Casablanca,
    quartier: "Sidi Moumen",
    telephone: "0655441122",
    description: "Dépannage coupure de courant. Éclairage LED.",
  },
  {
    id: 30,
    nom: "Othman Lazrak",
    metier: Profession.Gardener,
    ville: City.Rabat,
    quartier: "Temara",
    telephone: "0666777888",
    description: "Nettoyage de jardins et évacuation des déchets verts.",
  }
];

// Produits des Artisans
export const products: Product[] = [
    { 
        id: 1, 
        artisanId: 9, // Aicha Slaoui (Peintre)
        nom: "Tableau Tadelakt Ocre", 
        prix: 850, 
        description: "Peinture murale style Tadelakt, couleur ocre naturelle. Fait main.", 
        imageUrl: '../assets/images/background_poterie.jpg', 
        category: 'Décoration'
    },
    { 
        id: 2, 
        artisanId: 4, // Hassan El Fassi (Menuisier)
        nom: "Chaise en Bois de Cèdre sculpté", 
        prix: 1200, 
        description: "Chaise traditionnelle en cèdre, sculptée à la main. Pièce unique.", 
        imageUrl: '../assets/images/background_poterie.jpg', 
        category: 'Meubles'
    },
    { 
        id: 3, 
        artisanId: 7, // Samira Jilali (Maçon/Carrelage)
        nom: "Zellij Bleu et Blanc (1m²)", 
        prix: 550, 
        description: "Ensemble de carreaux de Zellij traditionnel (1m²), motifs géométriques bleus.", 
        imageUrl: '../assets/images/background_poterie.jpg', 
        category: 'Carrelage'
    },
    // Ajoutez plus de produits ici...
];
export const cities = Object.values(City);
export const professions = Object.values(Profession);